export const location = {
  Telangana: {
    Hyderabad: [
      "Gachibowli",
      "Hitech City",
      "Kondapur",
      "Madhapur",
      "Jubilee Hills",
      "Banjara Hills",
      "Manikonda",
      "Narsingi",
      "Kukatpally",
      "Miyapur",
      "Tellapur",
      "Financial District",
      "Nanakramguda",
      "Begumpet",
      "Uppal",
    ],
    Mahabubnagar: [
      "Bhageeratha Colony",
      "New Bus Stand",
      "New Town",
      "Rajendra Nagar",
      "Housing Board Colony",
      "Teachers Colony",
      "Mettugadda",
      "Padmavati Colony",
      "Srinivas Colony",
      "Yenugonda",
      "Boyapalle",
      "Christianpalle",
    ],
    // give me other regions too
    Warnagal: [
      "Hanamkonda",
      "Kazipet",
      "Waddepally",
      "Subedari",
      "Madikonda",
      "Desaipet Road",
      "Girimajipet",
      "Pochamma Maidan",
      "Bank Colony",
      "Warangal City Center",
    ],
    Adilabad: [
      "KRK Colony",
      "Bairamguda",
      "Vasanth Nagar",
      "New Town",
      "Hanuman Nagar",
      "Jawahar Nagar",
      "Bhavanipuram",
      "Rani Gunj",
      "Subhash Nagar",
      "Gandhi Nagar",
    ],
    Nizamabad: [
      "Vinayak Nagar",
      "Kanteshwar",
      "Bodhan",
      "Kamareddy",
      "Mubaraknagar",
      "Subhash Nagar",
      "Bank Colony",
      "Shivaji Nagar",
      "Armoor",
      "Madhavnagar",
    ],
  },
  "Andhra Pradesh": {
    Kurnool: [
      "Santosh Nagar",
      "Venkataramana Colony",
      "Nandikotkur Road",
      "Joharapuram Road",
      "Balaji Nagar",
      "Ganesh Nagar",
      "N R Peta",
      "New Krishna Nagar",
      "A Camp",
      "Dupadu",
    ],
    Vishakapatnam: [
      "Madhurawada",
      "Yendada",
      "MVP Colony",
      "Muralinagar",
      "Seethammadhara",
      "Siripuram",
      "Dwaraka Nagar",
      "Kirlampudi Layout",
      "Sheela Nagar",
      "Arilova",
    ],
    Tirupati: [
      "KT Road",
      "Mangalam Road",
      "Tiruchanoor",
      "Renigunta",
      "Yerpedu",
      "Avilala",
      "Chandragiri",
      "Karakambadi Road",
      "Padmavathipuram",
      "Air Bypass Road",
    ],
    Vijayawada: [
      "Benz Circle",
      "Madhura Nagar",
      "Kanuru",
      "Ajit Singh Nagar",
      "Tadigadapa",
      "Bhavanipuram",
      "Gollapudi",
      "Krishna Nagar",
      "Nunna",
      "Tadepalli",
    ],
  },
  "Tamil Nadu": {
    Chennai: [
      "Boat Club Road",
      "Poes Garden",
      "Anna Nagar",
      "Adyar",
      "Besant Nagar",
      "Mylapore",
      "Nungambakkam",
      "Velachery",
      "T. Nagar",
      "Porur",
    ],
    Coimbatore: [
      "Race Course",
      "Peelamedu",
      "Saibaba Colony",
      "RS Puram",
      "Singanallur",
      "Ganapathy",
      "Gandhipuram",
      "Saravanampatti",
      "Podanur",
      "Mettupalayam Road",
    ],
    Madura: [
      "Thiruparankundram",
      "Anna Nagar",
      "Goripalayam",
      "K.K. Nagar",
      "Madakulam",
      "Simmakkal",
      "Alagar Kovil",
      "Thathaneri",
      "Palanganatham",
      "Sellur",
    ],
    Tirupchirapalli: [
      "Cantonment",
      "Thillai Nagar",
      "KK Nagar",
      "Anna Nagar",
      "Srirangam",
      "Golden Rock",
      "Devadhanam",
      "Abhishekapatti",
      "Gandhi Nagar",
      "Panjapur",
    ],
    Tiruppur: [
      "Karumathampatti",
      "Velampalayam",
      "Madathukulam",
      "Avinashi",
      "Chinnakuyili",
      "Kundadam",
      "Moolapalayam",
      "Vellakovil",
      "Perumanallur",
      "Uthukuli",
    ],
  },
  Karnataka: {
    Bengaluru: [
      "Koramangala",
      "Indiranagar",
      "Whitefield",
      "Jayanagar",
      "HSR Layout",
      "Malleshwaram",
      "Bellandur",
      "Sarjapur Road",
      "Marathahalli",
      "Electronic City",
    ],
    Hubli: [
      "Vidyanagar",
      "Nagarkar Colony",
      "Anandnagar",
      "Siddarth Nagar",
      "Haripura",
      "Nehru Nagar",
      "Siddhivinayak Nagar",
      "Jayanagar",
      "Shivaji Nagar",
      "Mallya Nagar",
    ],
    Mysore: [
      "Kuvempu Nagar",
      "Jayalakshmipuram",
      "Saraswathipuram",
      "Bannimantap",
      "Gokulam",
      "Yadavagiri",
      "Vijayanagar",
      "Hebbal",
      "Vijayanagar 2nd Stage",
      "Hinkal",
    ],
    Belagaum: [
      "Gandhi Nagar",
      "Tilakwadi",
      "Alkapuri",
      "Station Road",
      "Shree Nagar",
      "Prashant Nagar",
      "Keshav Nagar",
      "Mangalwar Peth",
      "Kamati",
      "Hattargi",
    ],
    Manglore: [
      "Kodialbail",
      "Kadri",
      "Balmatta",
      "Bolar",
      "Kankanady",
      "Hampankatta",
      "Urwa",
      "Derebail",
      "Pandeshwar",
      "Bejai",
    ],
  },
  Maharashtra: {
    "Mumbai City": [
      "Colaba",
      "Fort",
      "Marine Drive",
      "Cuffe Parade",
      "Churchgate",
      "Malabar Hill",
      "Worli",
      "Grant Road",
      "Ballard Estate",
      "Nariman Point",
    ],
    "Mumbai Suburban": [
      "Bandra West",
      "Juhu",
      "Andheri West",
      "Powai",
      "Goregaon West",
      "Malad West",
      "Kandivali West",
      "Chembur",
      "Vile Parle West",
      "Borivali West",
    ],
    Pune: [
      "Koregaon Park",
      "Kalyani Nagar",
      "Baner",
      "Viman Nagar",
      "Aundh",
      "Wakad",
      "Hadapsar",
      "Hinjewadi",
      "Balewadi",
      "Kothrud",
    ],
    Nagpur: [
      "Dharampeth",
      "Sitabuldi",
      "Civil Lines",
      "Wardha Road",
      "Ramdaspeth",
      "Kalamna",
      "Dhantoli",
      "Jaripatka",
      "Hanuman Nagar",
      "Nehru Nagar",
    ],
    Nashik: [
      "Makhmalabad",
      "Gangapur Road",
      "College Road",
      "Pandav Nagar",
      "Indira Nagar",
      "Satpur",
      "CIDCO",
      "Deolali",
      "Dwarka",
      "Nashik Road",
    ],
  },
};
